### PR TITLE
Added support for fixing EOL's when applying settings if the current fil...

### PR DESCRIPTION
**Pull request by scottbilas**
...e has an EOL setting chosen for it.

This is important when using ReSharper, which only supports CRLF(*). If you have a file type set to LF, and then do any edits or refactors where ReSharper is involved, the file will get saved out with mixed EOL's. This commit will work around the ReSharper limitation.

(*) Is an issue for all ReSharpers up to at least 8.2.1; see https://youtrack.jetbrains.com/issue/RSRP-274916

### CODE REVIEW

**Comment by matiasbeckerle** [comment]
I'm here just to add +1 to this PR. Thanks for doing this :smile:.

**Comment by Mpdreamz** [comment]
LGTM :+1: pulling this in, thanks for submitting this @paweljasinski :smile:

**Comment by waynebloss** [comment]
Any idea when this will be released? I don't have ReSharper, but somehow I keep getting CRLFs in my javascript files.

**Comment by waynebloss** [comment]
For now I am using the [Line Endings Unifier](https://visualstudiogallery.msdn.microsoft.com/b2bbadd2-c337-43d7-9343-752ebbdd900f) extension, but it only works for `js` files and I need it to work for all sorts of file types.

**Comment by scottbilas** [comment]
this PR is no longer required

**Pull request closed without merging**
